[package]
name = "exploiting_blind_xxe_to_retrieve_data_via_error_messages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }
regex = "1.10.0"
text-colorizer = "1.0.0"
lazy_static = "1.4.0"
