[workspace]
members = [
    'Basic clickjacking with CSRF token protection',
    'Clickjacking with form input data prefilled from a URL parameter',
    'Clickjacking with a frame buster script',
    'Exploiting clickjacking vulnerability to trigger DOM-based XSS'
]
