[package]
name = "two_fa_simple_bypass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.3"
reqwest = { version = "0.11.20", features = ["blocking"] }
text-colorizer = "1.0.0"
