[package]
name = "exploiting_xxe_using_external_entities_to_retrieve_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
regex = "1.10.0"
reqwest = { version = "0.11.20", features = ["blocking", "multipart"] }
text-colorizer = "1.0.0"
