[package]
name = "exploiting_xxe_via_image_file_upload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = { version = "0.11.20", features = ["blocking", "multipart"] }
regex = "1.10.0"
text-colorizer = "1.0.0"
select = "0.6.0"
lazy_static = "1.4.0"
