[package]
name = "username_enumeration_via_account_lock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.3"
reqwest = { version = "0.11.19", features = ["blocking"] }
text-colorizer = "1.0.0"
lazy_static = "1.4.0"
