[package]
name = "two_fa_bypass_using_a_brute_force_attack_multi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"
regex = "1.6.0"
select = "0.5.0"
reqwest = { version = "0.11.20", features = ["blocking"] }
text-colorizer = "1.0.0"
lazy_static = "1.4.0"
