[workspace]
members = [
    'DOM XSS using web messages',
    'DOM XSS using web messages and a JavaScript URL',
    'DOM XSS using web messages and JSON.parse',
    'DOM-based open redirection',
    'DOM-based cookie manipulation'
]
