[workspace]
members = [
    'Accessing private GraphQL posts',
    'Accidental exposure of private GraphQL fields',
    'Finding a hidden GraphQL endpoint',
    'Bypassing GraphQL brute force protections'
]
