[package]
name = "auth_brute_force_cookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
md5 = "0.7.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
lazy_static = "1.4.0"
text-colorizer = "1.0.0"